apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2021-06-04T08:16:20Z'
  generation: 2
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:steps': {}
      manager: Mozilla
      operation: Update
      time: '2021-06-04T08:16:20Z'
  name: code-quality-analysis
  namespace: acstest
  selfLink: /apis/tekton.dev/v1beta1/namespaces/acstest/tasks/code-quality-analysis
  uid: 685b5aaf-7e20-47e9-af58-9ae03f7787ba
spec:
  steps:
    - command:
        - /bin/bash
        - '-c'
        - sleep 15
      image: registry.redhat.io/ubi7/ubi-minimal
      name: ''
      resources: {}
