apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  selfLink: /apis/tekton.dev/v1beta1/namespaces/acstest/pipelines/q-app-git
  name: q-app-git
  uid: 24d8aadc-f59f-4a92-8fb0-5d7e6f95d20b
  generation: 10
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:pipeline.openshift.io/runtime': {}
            'f:pipeline.openshift.io/type': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
  namespace: acstest
  labels:
    app.kubernetes.io/instance: q-app-git
    pipeline.openshift.io/runtime: java
    pipeline.openshift.io/type: kubernetes
spec:
  params:
    - default: q-app-git
      name: APP_NAME
      type: string
    - default: 'https://github.com/mglantz/q-app.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/acstest/q-app-git'
      name: image
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.image)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java-11
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: kubectl $@
        - name: ARGS
          value:
            - rollout
            - status
            - deploy/$(params.APP_NAME)
      runAfter:
        - custom-image-check
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: custom-image-scan
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: image
          value: $(params.image)
        - name: output_format
          value: json
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: custom-image-scan
    - name: custom-image-check
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: image
          value: $(params.image)
      runAfter:
        - custom-image-scan
      taskRef:
        kind: ClusterTask
        name: custom-image-check
  workspaces:
    - name: workspace
